#!/bin/bash

DIR_1=$1
START=$2
LENGT=$3

echo 'Preparing for mutation...'

./CH4cat $START $LENGT
./SAcat $START $LENGT
./HVcat $START $LENGT

mkdir $DIR_1
mv *.txt $DIR_1

./rmdata

cd ..
cp data/$DIR_1/* $DIR_1

echo '...done!'
